#!/usr/bin/env python3

import datetime
import subprocess
import logging
import os


RSYNC_DEFAULT_FLAGS = ['-a', '-v', '--delete']


class RsyncCompletedProcess(subprocess.CompletedProcess):

    @classmethod
    def from_parent(cls, parent):
        return cls(parent.args, parent.returncode,
                   parent.stdout, parent.stderr)

    def has_errors(self):
        """Return True if rsync exited with errors (return status is not 0)."""
        return self.returncode != 0

    def has_no_space_left_error(self):
        """Return True if a no space left error was detected.
        Check if stderr contains 'No space left on device (28)' or
        'Result too large (34)'.
        """
        return (b'No space left on device (28)' in self.stderr or
                b'Result too large (34)' in self.stderr)

    def assert_has_no_errors(self):
        """Raise an AssertionError return code is not 0."""
        if self.has_errors():
            err = 'rsync process had errors:\n' + self.stderr.decode('utf-8')
            raise AssertionError(err)


def rsync(source, dest, exe='rsync', flags=RSYNC_DEFAULT_FLAGS):
    """Run rsync.

    Args:
        source (str): path to source
        dest (str): path to destination
        exe (str): path to rsync executable
        flags (list[str]): flags to be passed to rsync

    Returns:
        RsyncCompletedProcess: rsync output data.
    """
    logging.info("rsync: starting copy")
    cmd = [exe] + flags + [source] + [dest]
    logging.debug("rsync command: {}".format(' '.join(cmd)))
    p = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    logging.info("rsync: done")
    return RsyncCompletedProcess.from_parent(p)


def send_email(exp, to, content, subject='', server='localhost'):
    raise RuntimeError("send_email: Not working yet")

    from email.mime.text import MIMEText
    import smtplib

    msg = MIMEText(content)
    msg['Subject'] = subject
    msg['From'] = exp
    msg['To'] = to

    s = smtplib.SMTP(server)
    s.send_message(msg)
    s.quit()


def now(fmt='%Y%m%d-%H%M%S'):
    """Return the date as a string in the format `fmt`.
    Args:
        fmt (str): date string format compatible with `datetime.strftime`.
    Returns:
        str: date as a string.
    """
    return datetime.datetime.today().strftime(fmt)


def main():
    source = 'tmp/source'
    dest = 'tmp/dest'

    # # Directory where log file will be written.
    # logfiledir = dest

    # # Create a log file.
    # logfile = os.path.join(logfiledir, now() + '_backup.log')
    # logging.info("logging to: {}".format(logfile))
    # logging.basicConfig(level=logging.DEBUG,
    #                     format='%(asctime)s - %(levelname)-8s %(message)s',
    #                     filename=logfile,
    #                     filemode='w')

    




if __name__ == '__main__':
    main()
